import type { PackageContent, PackageManifest } from '../../package-types'

export const retroGamesPackage = (): { manifest: PackageManifest; content: PackageContent } => ({
  manifest: {
    id: 'retro-games',
    name: 'Retro Games Arcade',
    version: '1.0.0',
    description:
      'Classic arcade games collection with high scores, leaderboards, and achievements. Includes Snake, Tetris, Pong, and more!',
    author: 'MetaBuilder Team',
    category: 'gaming',
    icon: '🕹️',
    screenshots: [],
    tags: ['games', 'arcade', 'retro', 'entertainment'],
    dependencies: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    downloadCount: 1567,
    rating: 4.9,
    installed: false,
  },
  content: {
    schemas: [
      {
        name: 'Game',
        displayName: 'Game',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'name', type: 'string', label: 'Name', required: true },
          { name: 'description', type: 'text', label: 'Description', required: false },
          { name: 'thumbnailUrl', type: 'string', label: 'Thumbnail URL', required: false },
          { name: 'gameType', type: 'string', label: 'Game Type', required: true },
          { name: 'difficulty', type: 'string', label: 'Difficulty', required: false },
          {
            name: 'playCount',
            type: 'number',
            label: 'Play Count',
            required: true,
            defaultValue: 0,
          },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'HighScore',
        displayName: 'High Score',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'gameId', type: 'string', label: 'Game ID', required: true },
          { name: 'userId', type: 'string', label: 'User ID', required: true },
          { name: 'playerName', type: 'string', label: 'Player Name', required: true },
          { name: 'score', type: 'number', label: 'Score', required: true },
          { name: 'level', type: 'number', label: 'Level Reached', required: false },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'Achievement',
        displayName: 'Achievement',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'name', type: 'string', label: 'Name', required: true },
          { name: 'description', type: 'text', label: 'Description', required: false },
          { name: 'gameId', type: 'string', label: 'Game ID', required: true },
          { name: 'iconUrl', type: 'string', label: 'Icon URL', required: false },
          { name: 'requirement', type: 'string', label: 'Requirement', required: true },
          { name: 'points', type: 'number', label: 'Points', required: true, defaultValue: 10 },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'UserAchievement',
        displayName: 'User Achievement',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'userId', type: 'string', label: 'User ID', required: true },
          { name: 'achievementId', type: 'string', label: 'Achievement ID', required: true },
          { name: 'unlockedAt', type: 'number', label: 'Unlocked At', required: true },
        ],
      },
    ],
    pages: [
      {
        id: 'page_arcade_home',
        path: '/arcade',
        title: 'Arcade Home',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_game_play',
        path: '/arcade/play/:id',
        title: 'Play Game',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_leaderboard',
        path: '/arcade/leaderboard',
        title: 'Leaderboard',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
    ],
    workflows: [],
    componentHierarchy: {},
    componentConfigs: {},
    seedData: {
      Game: [
        {
          id: 'game_snake',
          name: 'Snake',
          description: 'Classic snake game',
          gameType: 'snake',
          difficulty: 'medium',
          playCount: 0,
          createdAt: Date.now(),
        },
        {
          id: 'game_tetris',
          name: 'Tetris',
          description: 'Block-stacking puzzle',
          gameType: 'tetris',
          difficulty: 'medium',
          playCount: 0,
          createdAt: Date.now(),
        },
        {
          id: 'game_pong',
          name: 'Pong',
          description: 'Classic paddle game',
          gameType: 'pong',
          difficulty: 'easy',
          playCount: 0,
          createdAt: Date.now(),
        },
      ],
    },
  },
})
