{
  "id": "layshaft",
  "name": "Layshaft Assembly",
  "partNumber": "FD-1848315",
  "material": "steel",
  "quantity": 1,
  "weight": 3200.0,
  "weightUnit": "g",
  "baseY": 160,
  "description": "Counter shaft with integrated gear cluster",
  "installation": {
    "tools": [
      { "name": "Bearing puller", "size": "25-50mm", "required": true },
      { "name": "Hydraulic press", "size": "10 ton", "required": true },
      { "name": "Dial indicator", "size": "-", "required": true },
      { "name": "Magnetic base", "size": "-", "required": true }
    ],
    "hardware": [
      { "name": "Layshaft bearing (front)", "spec": "6305-2RS", "qty": 1, "reusable": false },
      { "name": "Layshaft bearing (rear)", "spec": "6206-2RS", "qty": 1, "reusable": false },
      { "name": "Thrust washer", "spec": "25x35x2.5", "qty": 2, "reusable": true }
    ],
    "torque": [],
    "notes": [
      "Check gear teeth for pitting or wear",
      "Measure bearing journal diameters",
      "Verify end float: 0.10-0.25mm",
      "Heat bearings to 80Â°C for installation"
    ]
  },
  "geometry": [
    { "type": "cylinder", "rx": 14, "ry": 5, "height": 120 },
    { "type": "gearRing", "teeth": 24, "outerRadius": 28, "toothHeight": 5, "offsetY": -40 },
    { "type": "gearRing", "teeth": 20, "outerRadius": 24, "toothHeight": 5, "offsetY": -15 },
    { "type": "gearRing", "teeth": 18, "outerRadius": 22, "toothHeight": 5, "offsetY": 10 },
    { "type": "gearRing", "teeth": 16, "outerRadius": 20, "toothHeight": 5, "offsetY": 35 }
  ],
  "geometry3d": [
    { "type": "cylinder", "r": 10, "height": 140, "fill": "#888" },
    { "type": "cylinder", "r": 28, "height": 12, "offsetZ": -55, "fill": "#666" },
    { "type": "cylinder", "r": 24, "height": 12, "offsetZ": -35, "fill": "#666" },
    { "type": "cylinder", "r": 20, "height": 12, "offsetZ": -15, "fill": "#666" },
    { "type": "cylinder", "r": 18, "height": 12, "offsetZ": 5, "fill": "#666" },
    { "type": "cylinder", "r": 16, "height": 12, "offsetZ": 25, "fill": "#666" },
    { "type": "cylinder", "r": 30, "height": 14, "offsetZ": 50, "fill": "#555" }
  ]
}
