#include "prisma_generator.hpp"
#include <sstream>

namespace dbal {
namespace core {

std::string PrismaGenerator::generateSchema(const std::map<std::string, EntitySchema>& schemas) {
    std::ostringstream out;

    // Header comment
    out << "// This file was auto-generated by C++ DBAL from YAML entity schemas\n";
    out << "// Source: /dbal/shared/api/schema/entities/\n";
    out << "// Generator: dbal/production/src/core/prisma_generator.cpp\n";
    out << "// DO NOT EDIT MANUALLY - changes will be overwritten\n\n";

    // Datasource
    out << datasourceGenerator.generateDatasource() << "\n\n";

    // Client
    out << datasourceGenerator.generateClient() << "\n\n";

    // Models
    for (const auto& [name, schema] : schemas) {
        // Generate model with fields
        out << modelGenerator.generateModel(schema);

        // Generate relations (if any)
        if (!schema.relations.empty()) {
            out << "\n";
            for (const auto& rel : schema.relations) {
                out << "  " << relationGenerator.generateRelation(rel) << "\n";
            }
        }

        out << "\n\n";
    }

    return out.str();
}

std::filesystem::path PrismaGenerator::writeToTempFile(const std::string& schema) {
    return PrismaFileWriter::writeToTempFile(schema);
}

std::filesystem::path PrismaGenerator::getTempDir() {
    return PrismaFileWriter::getTempDir();
}

} // namespace core
} // namespace dbal
