// Auto-generated exports - DO NOT EDIT MANUALLY
// All atoms now use JSON-based definitions from @/lib/json-ui/json-components
// Metabuilder* names are canonical; old names are aliases for backward compatibility
export {
  MetabuilderWidgetAccordion,
  MetabuilderFormActionButton,
  MetabuilderLayoutActionCard,
  MetabuilderDisplayActionIcon,
  MetabuilderFeedbackAlert,
  MetabuilderWidgetAppBranding,
  MetabuilderWidgetAppDialogs,
  MetabuilderWidgetAppHeader,
  MetabuilderWidgetAppLayout,
  MetabuilderWidgetAppLogo,
  MetabuilderWidgetAppMainPanel,
  MetabuilderWidgetAppRouterLayout,
  MetabuilderDisplayAvatar,
  MetabuilderDisplayAvatarGroup,
  MetabuilderDisplayBadge,
  MetabuilderWidgetBindingEditor,
  MetabuilderWidgetBindingIndicator,
  MetabuilderNavBreadcrumb,
  MetabuilderFormButton,
  MetabuilderFormButtonGroup,
  MetabuilderWidgetCalendar,
  MetabuilderWidgetCanvasRenderer,
  MetabuilderLayoutCard,
  MetabuilderFormCheckbox,
  MetabuilderWidgetChip,
  MetabuilderDisplayCircularProgress,
  MetabuilderDisplayCode,
  MetabuilderLayoutCodeExplanationDialog,
  MetabuilderWidgetColorSwatch,
  MetabuilderWidgetCommandPalette,
  MetabuilderLayoutCompletionCard,
  MetabuilderLayoutComponentBindingDialog,
  MetabuilderWidgetComponentPalette,
  MetabuilderWidgetComponentPaletteItem,
  MetabuilderWidgetComponentTree,
  MetabuilderWidgetComponentTreeNode,
  MetabuilderFormConfirmButton,
  MetabuilderLayoutContainer,
  MetabuilderNavContextMenu,
  MetabuilderFormCopyButton,
  MetabuilderFeedbackCountBadge,
  MetabuilderDataDataList,
  MetabuilderFeedbackDataSourceBadge,
  MetabuilderLayoutDataSourceCard,
  MetabuilderLayoutDataSourceEditorDialog,
  MetabuilderDataDataSourceManager,
  MetabuilderDataDataTable,
  MetabuilderFormDatePicker,
  MetabuilderWidgetDetailRow,
  Dialog,
  MetabuilderDisplayDivider,
  MetabuilderWidgetDot,
  MetabuilderLayoutDrawer,
  DropdownMenu,
  MetabuilderFeedbackEmptyCanvasState,
  MetabuilderFeedbackEmptyMessage,
  MetabuilderFeedbackEmptyState,
  MetabuilderFeedbackEmptyStateIcon,
  MetabuilderFeedbackErrorBadge,
  MetabuilderDisplayFileIcon,
  MetabuilderFormFileUpload,
  MetabuilderFormFilterInput,
  MetabuilderLayoutFlex,
  MetabuilderFormForm,
  MetabuilderFormFormField,
  MetabuilderFeedbackGitHubBuildStatus,
  MetabuilderLayoutGlowCard,
  MetabuilderLayoutGrid,
  MetabuilderDisplayHeading,
  MetabuilderDisplayHelperText,
  MetabuilderLayoutHoverCard,
  MetabuilderDisplayIcon,
  MetabuilderFormIconButton,
  MetabuilderDisplayIconText,
  MetabuilderDisplayIconWrapper,
  MetabuilderDisplayImage,
  MetabuilderFeedbackInfoBox,
  MetabuilderWidgetInfoPanel,
  MetabuilderFormInput,
  MetabuilderFormInputOTP,
  MetabuilderWidgetKbd,
  MetabuilderDataKeyValue,
  MetabuilderDisplayLabel,
  MetabuilderDataLazyD3BarChart,
  MetabuilderNavLink,
  MetabuilderDataList,
  MetabuilderDataListItem,
  MetabuilderWidgetLiveIndicator,
  MetabuilderFeedbackLoadingFallback,
  MetabuilderFeedbackLoadingSpinner,
  MetabuilderFeedbackLoadingState,
  MetabuilderNavMenu,
  MetabuilderDataMetricCard,
  MetabuilderDataMetricDisplay,
  MetabuilderLayoutModal,
  MetabuilderNavNavigationItem,
  MetabuilderNavNavigationMenu,
  MetabuilderFeedbackNotification,
  MetabuilderFormNumberInput,
  MetabuilderWidgetPageHeader,
  MetabuilderWidgetPageHeaderContent,
  Pagination,
  MetabuilderWidgetPanelHeader,
  MetabuilderFormPasswordInput,
  MetabuilderWidgetPopover,
  Progress,
  MetabuilderDisplayProgressBar,
  MetabuilderWidgetPropertyEditorField,
  MetabuilderWidgetPulse,
  MetabuilderFormQuickActionButton,
  MetabuilderFormRadioGroup,
  MetabuilderFormRangeSlider,
  MetabuilderWidgetRating,
  MetabuilderLayoutResponsiveGrid,
  MetabuilderWidgetSaveIndicator,
  MetabuilderDisplaySchemaCodeViewer,
  MetabuilderWidgetSchemaEditorCanvas,
  MetabuilderWidgetSchemaEditorLayout,
  MetabuilderWidgetSchemaEditorPropertiesPanel,
  MetabuilderWidgetSchemaEditorSidebar,
  MetabuilderFeedbackSchemaEditorStatusBar,
  MetabuilderWidgetSchemaEditorToolbar,
  MetabuilderWidgetScrollArea,
  MetabuilderDisplayScrollAreaThumb,
  MetabuilderWidgetSearchInput,
  MetabuilderLayoutSection,
  MetabuilderDataSeedDataManager,
  MetabuilderFeedbackSeedDataStatus,
  MetabuilderFormSelect,
  MetabuilderDisplaySeparator,
  MetabuilderDisplaySkeleton,
  MetabuilderFormSlider,
  MetabuilderWidgetSpacer,
  MetabuilderWidgetSparkle,
  MetabuilderDisplaySpinner,
  MetabuilderLayoutStack,
  MetabuilderDataStatCard,
  MetabuilderFeedbackStatusBadge,
  MetabuilderFeedbackStatusIcon,
  MetabuilderWidgetStepIndicator,
  MetabuilderWidgetStepper,
  MetabuilderWidgetStorageSettings,
  MetabuilderFormSwitch,
  MetabuilderNavTabIcon,
  MetabuilderDataTable,
  MetabuilderNavTabs,
  MetabuilderDisplayTag,
  MetabuilderDisplayText,
  MetabuilderFormTextArea,
  MetabuilderDisplayTextGradient,
  MetabuilderDisplayTextHighlight,
  MetabuilderDataTimeline,
  MetabuilderWidgetTimestamp,
  MetabuilderLayoutTipsCard,
  MetabuilderFormToggle,
  MetabuilderWidgetToolbarActions,
  MetabuilderWidgetTooltip,
  MetabuilderLayoutTreeCard,
  MetabuilderDisplayTreeIcon,
  MetabuilderDataTreeListPanel,
  MetabuilderWidgetAccordion as Accordion,
  MetabuilderFormActionButton as ActionButton,
  MetabuilderLayoutActionCard as ActionCard,
  MetabuilderDisplayActionIcon as ActionIcon,
  MetabuilderFeedbackAlert as Alert,
  MetabuilderWidgetAppBranding as AppBranding,
  MetabuilderWidgetAppHeader as AppHeader,
  MetabuilderWidgetAppLogo as AppLogo,
  MetabuilderDisplayAvatar as Avatar,
  MetabuilderDisplayAvatarGroup as AvatarGroup,
  MetabuilderDisplayBadge as Badge,
  MetabuilderWidgetBindingEditor as BindingEditor,
  MetabuilderWidgetBindingIndicator as BindingIndicator,
  MetabuilderNavBreadcrumb as Breadcrumb,
  MetabuilderFormButton as Button,
  MetabuilderFormButtonGroup as ButtonGroup,
  MetabuilderWidgetCalendar as Calendar,
  MetabuilderWidgetCanvasRenderer as CanvasRenderer,
  MetabuilderLayoutCard as Card,
  MetabuilderFormCheckbox as Checkbox,
  MetabuilderWidgetChip as Chip,
  MetabuilderDisplayCircularProgress as CircularProgress,
  MetabuilderDisplayCode as Code,
  MetabuilderLayoutCodeExplanationDialog as CodeExplanationDialog,
  MetabuilderWidgetColorSwatch as ColorSwatch,
  MetabuilderWidgetCommandPalette as CommandPalette,
  MetabuilderLayoutCompletionCard as CompletionCard,
  MetabuilderLayoutComponentBindingDialog as ComponentBindingDialog,
  MetabuilderWidgetComponentPalette as ComponentPalette,
  MetabuilderWidgetComponentPaletteItem as ComponentPaletteItem,
  MetabuilderWidgetComponentTree as ComponentTree,
  MetabuilderWidgetComponentTreeNode as ComponentTreeNode,
  MetabuilderFormConfirmButton as ConfirmButton,
  MetabuilderLayoutContainer as Container,
  MetabuilderNavContextMenu as ContextMenu,
  MetabuilderFormCopyButton as CopyButton,
  MetabuilderFeedbackCountBadge as CountBadge,
  MetabuilderDataDataList as DataList,
  MetabuilderFeedbackDataSourceBadge as DataSourceBadge,
  MetabuilderLayoutDataSourceCard as DataSourceCard,
  MetabuilderLayoutDataSourceEditorDialog as DataSourceEditorDialog,
  MetabuilderDataDataSourceManager as DataSourceManager,
  MetabuilderDataDataTable as DataTable,
  MetabuilderFormDatePicker as DatePicker,
  MetabuilderWidgetDetailRow as DetailRow,
  MetabuilderDisplayDivider as Divider,
  MetabuilderWidgetDot as Dot,
  MetabuilderLayoutDrawer as Drawer,
  MetabuilderFeedbackEmptyCanvasState as EmptyCanvasState,
  MetabuilderFeedbackEmptyMessage as EmptyMessage,
  MetabuilderFeedbackEmptyState as EmptyState,
  MetabuilderFeedbackEmptyStateIcon as EmptyStateIcon,
  MetabuilderFeedbackErrorBadge as ErrorBadge,
  MetabuilderDisplayFileIcon as FileIcon,
  MetabuilderFormFileUpload as FileUpload,
  MetabuilderFormFilterInput as FilterInput,
  MetabuilderLayoutFlex as Flex,
  MetabuilderFormForm as Form,
  MetabuilderFeedbackGitHubBuildStatus as GitHubBuildStatus,
  MetabuilderLayoutGlowCard as GlowCard,
  MetabuilderLayoutGrid as Grid,
  MetabuilderDisplayHeading as Heading,
  MetabuilderDisplayHelperText as HelperText,
  MetabuilderLayoutHoverCard as HoverCard,
  MetabuilderDisplayIcon as Icon,
  MetabuilderFormIconButton as IconButton,
  MetabuilderDisplayIconText as IconText,
  MetabuilderDisplayIconWrapper as IconWrapper,
  MetabuilderDisplayImage as Image,
  MetabuilderFeedbackInfoBox as InfoBox,
  MetabuilderWidgetInfoPanel as InfoPanel,
  MetabuilderFormInput as Input,
  MetabuilderWidgetKbd as Kbd,
  MetabuilderDataKeyValue as KeyValue,
  MetabuilderDisplayLabel as Label,
  MetabuilderDataLazyD3BarChart as LazyD3BarChart,
  MetabuilderNavLink as Link,
  MetabuilderDataList as List,
  MetabuilderDataListItem as ListItem,
  MetabuilderWidgetLiveIndicator as LiveIndicator,
  MetabuilderFeedbackLoadingFallback as LoadingFallback,
  MetabuilderFeedbackLoadingSpinner as LoadingSpinner,
  MetabuilderFeedbackLoadingState as LoadingState,
  MetabuilderNavMenu as Menu,
  MetabuilderDataMetricCard as MetricCard,
  MetabuilderDataMetricDisplay as MetricDisplay,
  MetabuilderLayoutModal as Modal,
  MetabuilderNavNavigationItem as NavigationItem,
  MetabuilderFeedbackNotification as Notification,
  MetabuilderFormNumberInput as NumberInput,
  MetabuilderWidgetPageHeader as PageHeader,
  MetabuilderWidgetPageHeaderContent as PageHeaderContent,
  MetabuilderWidgetPanelHeader as PanelHeader,
  MetabuilderFormPasswordInput as PasswordInput,
  MetabuilderWidgetPopover as Popover,
  MetabuilderDisplayProgressBar as ProgressBar,
  MetabuilderWidgetPropertyEditorField as PropertyEditorField,
  MetabuilderWidgetPulse as Pulse,
  MetabuilderFormQuickActionButton as QuickActionButton,
  MetabuilderFormRadioGroup as RadioGroup,
  MetabuilderFormRangeSlider as RangeSlider,
  MetabuilderWidgetRating as Rating,
  MetabuilderLayoutResponsiveGrid as ResponsiveGrid,
  MetabuilderWidgetSaveIndicator as SaveIndicator,
  MetabuilderDisplaySchemaCodeViewer as SchemaCodeViewer,
  MetabuilderWidgetSchemaEditorCanvas as SchemaEditorCanvas,
  MetabuilderWidgetSchemaEditorLayout as SchemaEditorLayout,
  MetabuilderWidgetSchemaEditorPropertiesPanel as SchemaEditorPropertiesPanel,
  MetabuilderWidgetSchemaEditorSidebar as SchemaEditorSidebar,
  MetabuilderFeedbackSchemaEditorStatusBar as SchemaEditorStatusBar,
  MetabuilderWidgetSchemaEditorToolbar as SchemaEditorToolbar,
  MetabuilderWidgetScrollArea as ScrollArea,
  MetabuilderDisplayScrollAreaThumb as ScrollAreaThumb,
  MetabuilderWidgetSearchInput as SearchInput,
  MetabuilderLayoutSection as Section,
  MetabuilderDataSeedDataManager as SeedDataManager,
  MetabuilderFeedbackSeedDataStatus as SeedDataStatus,
  MetabuilderFormSelect as Select,
  MetabuilderDisplaySeparator as Separator,
  MetabuilderDisplaySkeleton as Skeleton,
  MetabuilderFormSlider as Slider,
  MetabuilderWidgetSpacer as Spacer,
  MetabuilderWidgetSparkle as Sparkle,
  MetabuilderDisplaySpinner as Spinner,
  MetabuilderLayoutStack as Stack,
  MetabuilderDataStatCard as StatCard,
  MetabuilderFeedbackStatusBadge as StatusBadge,
  MetabuilderFeedbackStatusIcon as StatusIcon,
  MetabuilderWidgetStepIndicator as StepIndicator,
  MetabuilderWidgetStepper as Stepper,
  MetabuilderWidgetStorageSettings as StorageSettings,
  MetabuilderFormSwitch as Switch,
  MetabuilderNavTabIcon as TabIcon,
  MetabuilderDataTable as Table,
  MetabuilderNavTabs as Tabs,
  MetabuilderDisplayTag as Tag,
  MetabuilderDisplayText as Text,
  MetabuilderFormTextArea as TextArea,
  MetabuilderDisplayTextGradient as TextGradient,
  MetabuilderDisplayTextHighlight as TextHighlight,
  MetabuilderDataTimeline as Timeline,
  MetabuilderWidgetTimestamp as Timestamp,
  MetabuilderLayoutTipsCard as TipsCard,
  MetabuilderFormToggle as Toggle,
  MetabuilderWidgetToolbarActions as ToolbarActions,
  MetabuilderWidgetTooltip as Tooltip,
  MetabuilderLayoutTreeCard as TreeCard,
  MetabuilderDisplayTreeIcon as TreeIcon,
  MetabuilderDataTreeListPanel as TreeListPanel,
  MetabuilderFormFormField as FormField,
  MetabuilderFormInputOTP as InputOTP,
  MetabuilderNavNavigationMenu as NavigationMenu,
  MetabuilderWidgetAppDialogs as AppDialogs,
  MetabuilderWidgetAppLayout as AppLayout,
  MetabuilderWidgetAppMainPanel as AppMainPanel,
  MetabuilderWidgetAppRouterLayout as AppRouterLayout,
} from '@/lib/json-ui/json-components'
