name: ✨ Feature Request
description: Suggest a new feature or enhancement for MetaBuilder
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving MetaBuilder! Please describe your feature request in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe what you're trying to achieve.
      placeholder: I'm frustrated when... / I need to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like MetaBuilder to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... but...

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: Which part of MetaBuilder would this feature affect?
      options:
        - Frontend (Next.js UI)
        - Backend (API/Auth)
        - Database (Prisma/Schema)
        - DBAL (TypeScript/C++)
        - Package System
        - Lua Scripting
        - Multi-Tenant System
        - Permission System (Levels 1-6)
        - Workflows
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High (Blocker for my use case)
        - Medium (Would be very helpful)
        - Low (Nice to have)
    validations:
      required: true

  - type: dropdown
    id: user-level
    attributes:
      label: Target User Level
      description: Which permission level(s) would use this feature?
      multiple: true
      options:
        - Level 1 (Public)
        - Level 2 (User)
        - Level 3 (Moderator)
        - Level 4 (Admin)
        - Level 5 (God)
        - Level 6 (Supergod)
        - All levels

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases or examples of how this feature would be used
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [scenario], this feature would help by [outcome]

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, implementation ideas, or constraints?
      placeholder: |
        - This might require changes to...
        - Could be implemented using...
        - May affect performance of...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add any mockups, diagrams, or examples (drag and drop images or links)
      placeholder: Paste images or links here...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to submit a PR for this feature
          required: false
        - label: I can help with testing this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: This feature aligns with MetaBuilder's data-driven, multi-tenant architecture
          required: true
        - label: I have provided sufficient detail for others to understand the request
          required: true
