import type { PackageContent, PackageManifest } from '../../package-types'

export const forumClassicPackage = (): { manifest: PackageManifest; content: PackageContent } => ({
  manifest: {
    id: 'forum-classic',
    name: 'Classic Forum',
    version: '1.0.0',
    description:
      'Full-featured discussion forum with threads, categories, user profiles, and moderation tools. Perfect for building community discussions.',
    author: 'MetaBuilder Team',
    category: 'social',
    icon: '💬',
    screenshots: [],
    tags: ['forum', 'discussion', 'community', 'threads'],
    dependencies: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    downloadCount: 1247,
    rating: 4.7,
    installed: false,
  },
  content: {
    schemas: [
      {
        name: 'ForumCategory',
        displayName: 'Forum Category',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'name', type: 'string', label: 'Category Name', required: true },
          { name: 'description', type: 'text', label: 'Description', required: false },
          {
            name: 'order',
            type: 'number',
            label: 'Display Order',
            required: true,
            defaultValue: 0,
          },
          { name: 'icon', type: 'string', label: 'Icon', required: false },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'ForumThread',
        displayName: 'Forum Thread',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'categoryId', type: 'string', label: 'Category ID', required: true },
          { name: 'title', type: 'string', label: 'Thread Title', required: true },
          { name: 'authorId', type: 'string', label: 'Author ID', required: true },
          { name: 'content', type: 'text', label: 'Content', required: true },
          {
            name: 'isPinned',
            type: 'boolean',
            label: 'Pinned',
            required: false,
            defaultValue: false,
          },
          {
            name: 'isLocked',
            type: 'boolean',
            label: 'Locked',
            required: false,
            defaultValue: false,
          },
          { name: 'views', type: 'number', label: 'View Count', required: true, defaultValue: 0 },
          {
            name: 'replyCount',
            type: 'number',
            label: 'Reply Count',
            required: true,
            defaultValue: 0,
          },
          { name: 'lastReplyAt', type: 'number', label: 'Last Reply At', required: false },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
          { name: 'updatedAt', type: 'number', label: 'Updated At', required: false },
        ],
      },
      {
        name: 'ForumPost',
        displayName: 'Forum Post',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'threadId', type: 'string', label: 'Thread ID', required: true },
          { name: 'authorId', type: 'string', label: 'Author ID', required: true },
          { name: 'content', type: 'text', label: 'Content', required: true },
          { name: 'likes', type: 'number', label: 'Like Count', required: true, defaultValue: 0 },
          {
            name: 'isEdited',
            type: 'boolean',
            label: 'Edited',
            required: false,
            defaultValue: false,
          },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
          { name: 'updatedAt', type: 'number', label: 'Updated At', required: false },
        ],
      },
    ],
    pages: [
      {
        id: 'page_forum_home',
        path: '/forum',
        title: 'Forum Home',
        level: 2,
        componentTree: [],
        requiresAuth: true,
        requiredRole: 'user',
      },
      {
        id: 'page_forum_category',
        path: '/forum/category/:id',
        title: 'Forum Category',
        level: 2,
        componentTree: [],
        requiresAuth: true,
        requiredRole: 'user',
      },
      {
        id: 'page_forum_thread',
        path: '/forum/thread/:id',
        title: 'Forum Thread',
        level: 2,
        componentTree: [],
        requiresAuth: true,
        requiredRole: 'user',
      },
    ],
    workflows: [
      {
        id: 'workflow_create_thread',
        name: 'Create Forum Thread',
        description: 'Workflow for creating a new forum thread',
        nodes: [],
        edges: [],
        enabled: true,
      },
      {
        id: 'workflow_post_reply',
        name: 'Post Forum Reply',
        description: 'Workflow for posting a reply to a thread',
        nodes: [],
        edges: [],
        enabled: true,
      },
    ],
    componentHierarchy: {},
    componentConfigs: {},
    seedData: {
      ForumCategory: [
        {
          id: 'cat_1',
          name: 'General Discussion',
          description: 'Talk about anything',
          order: 1,
          icon: '💭',
          createdAt: Date.now(),
        },
        {
          id: 'cat_2',
          name: 'Announcements',
          description: 'Official announcements',
          order: 0,
          icon: '📢',
          createdAt: Date.now(),
        },
      ],
    },
  },
})
