import type { PackageContent, PackageManifest } from '../../package-types'

export const spotifyClonePackage = (): { manifest: PackageManifest; content: PackageContent } => ({
  manifest: {
    id: 'spotify-clone',
    name: 'Music Streaming Platform',
    version: '1.0.0',
    description:
      'Full music streaming service with playlists, albums, artists, search, and playback controls. Create your own Spotify!',
    author: 'MetaBuilder Team',
    category: 'entertainment',
    icon: '🎵',
    screenshots: [],
    tags: ['music', 'streaming', 'audio', 'spotify'],
    dependencies: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    downloadCount: 1823,
    rating: 4.6,
    installed: false,
  },
  content: {
    schemas: [
      {
        name: 'Artist',
        displayName: 'Artist',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'name', type: 'string', label: 'Name', required: true },
          { name: 'bio', type: 'text', label: 'Biography', required: false },
          { name: 'imageUrl', type: 'string', label: 'Image URL', required: false },
          { name: 'genre', type: 'string', label: 'Genre', required: false },
          {
            name: 'verified',
            type: 'boolean',
            label: 'Verified',
            required: true,
            defaultValue: false,
          },
          {
            name: 'followers',
            type: 'number',
            label: 'Followers',
            required: true,
            defaultValue: 0,
          },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'Album',
        displayName: 'Album',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'title', type: 'string', label: 'Title', required: true },
          { name: 'artistId', type: 'string', label: 'Artist ID', required: true },
          { name: 'coverUrl', type: 'string', label: 'Cover URL', required: false },
          { name: 'releaseDate', type: 'number', label: 'Release Date', required: false },
          { name: 'genre', type: 'string', label: 'Genre', required: false },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'Track',
        displayName: 'Track',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'title', type: 'string', label: 'Title', required: true },
          { name: 'artistId', type: 'string', label: 'Artist ID', required: true },
          { name: 'albumId', type: 'string', label: 'Album ID', required: false },
          { name: 'audioUrl', type: 'string', label: 'Audio URL', required: true },
          { name: 'duration', type: 'number', label: 'Duration (seconds)', required: true },
          { name: 'trackNumber', type: 'number', label: 'Track Number', required: false },
          { name: 'plays', type: 'number', label: 'Play Count', required: true, defaultValue: 0 },
          { name: 'likes', type: 'number', label: 'Likes', required: true, defaultValue: 0 },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'MusicPlaylist',
        displayName: 'Playlist',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'name', type: 'string', label: 'Name', required: true },
          { name: 'description', type: 'text', label: 'Description', required: false },
          { name: 'ownerId', type: 'string', label: 'Owner ID', required: true },
          { name: 'coverUrl', type: 'string', label: 'Cover URL', required: false },
          { name: 'trackIds', type: 'json', label: 'Track IDs', required: true },
          {
            name: 'isPublic',
            type: 'boolean',
            label: 'Public',
            required: true,
            defaultValue: true,
          },
          {
            name: 'followers',
            type: 'number',
            label: 'Followers',
            required: true,
            defaultValue: 0,
          },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
    ],
    pages: [
      {
        id: 'page_music_home',
        path: '/music',
        title: 'Music Home',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_music_search',
        path: '/search',
        title: 'Search Music',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_music_artist',
        path: '/artist/:id',
        title: 'Artist',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_music_album',
        path: '/album/:id',
        title: 'Album',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_music_playlist',
        path: '/playlist/:id',
        title: 'Playlist',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
    ],
    workflows: [],
    componentHierarchy: {},
    componentConfigs: {},
  },
})
