import type { PackageContent, PackageManifest } from '../../package-types'

export const youtubeClonePackage = (): { manifest: PackageManifest; content: PackageContent } => ({
  manifest: {
    id: 'youtube-clone',
    name: 'Video Platform',
    version: '1.0.0',
    description:
      'Complete video sharing platform with upload, streaming, comments, likes, subscriptions, and playlists. Build your own YouTube!',
    author: 'MetaBuilder Team',
    category: 'entertainment',
    icon: '🎥',
    screenshots: [],
    tags: ['video', 'streaming', 'media', 'youtube'],
    dependencies: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    downloadCount: 2156,
    rating: 4.8,
    installed: false,
  },
  content: {
    schemas: [
      {
        name: 'Video',
        displayName: 'Video',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'title', type: 'string', label: 'Title', required: true },
          { name: 'description', type: 'text', label: 'Description', required: false },
          { name: 'uploaderId', type: 'string', label: 'Uploader ID', required: true },
          { name: 'videoUrl', type: 'string', label: 'Video URL', required: true },
          { name: 'thumbnailUrl', type: 'string', label: 'Thumbnail URL', required: false },
          { name: 'duration', type: 'number', label: 'Duration (seconds)', required: true },
          { name: 'views', type: 'number', label: 'Views', required: true, defaultValue: 0 },
          { name: 'likes', type: 'number', label: 'Likes', required: true, defaultValue: 0 },
          { name: 'dislikes', type: 'number', label: 'Dislikes', required: true, defaultValue: 0 },
          { name: 'category', type: 'string', label: 'Category', required: false },
          { name: 'tags', type: 'json', label: 'Tags', required: false },
          {
            name: 'published',
            type: 'boolean',
            label: 'Published',
            required: true,
            defaultValue: false,
          },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'VideoComment',
        displayName: 'Video Comment',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'videoId', type: 'string', label: 'Video ID', required: true },
          { name: 'userId', type: 'string', label: 'User ID', required: true },
          { name: 'content', type: 'text', label: 'Content', required: true },
          { name: 'likes', type: 'number', label: 'Likes', required: true, defaultValue: 0 },
          { name: 'parentId', type: 'string', label: 'Parent Comment ID', required: false },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'Subscription',
        displayName: 'Subscription',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'subscriberId', type: 'string', label: 'Subscriber ID', required: true },
          { name: 'channelId', type: 'string', label: 'Channel ID', required: true },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
      {
        name: 'Playlist',
        displayName: 'Playlist',
        fields: [
          { name: 'id', type: 'string', label: 'ID', required: true, primaryKey: true },
          { name: 'name', type: 'string', label: 'Name', required: true },
          { name: 'description', type: 'text', label: 'Description', required: false },
          { name: 'ownerId', type: 'string', label: 'Owner ID', required: true },
          { name: 'videoIds', type: 'json', label: 'Video IDs', required: true },
          {
            name: 'isPublic',
            type: 'boolean',
            label: 'Public',
            required: true,
            defaultValue: true,
          },
          { name: 'createdAt', type: 'number', label: 'Created At', required: true },
        ],
      },
    ],
    pages: [
      {
        id: 'page_video_home',
        path: '/videos',
        title: 'Video Home',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_video_watch',
        path: '/watch/:id',
        title: 'Watch Video',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
      {
        id: 'page_video_upload',
        path: '/upload',
        title: 'Upload Video',
        level: 2,
        componentTree: [],
        requiresAuth: true,
        requiredRole: 'user',
      },
      {
        id: 'page_channel',
        path: '/channel/:id',
        title: 'Channel',
        level: 2,
        componentTree: [],
        requiresAuth: false,
      },
    ],
    workflows: [],
    componentHierarchy: {},
    componentConfigs: {},
  },
})
