# Product seed data
# DBAL entity: Product
# Schema reference: dbal/shared/api/schema/entities/ecommerce/product.yaml
entity: Product
version: "1.0"
package: ecommerce-basic
description: "Sample e-commerce product catalog"

records:
  - id: prod_laptop_pro
    tenantId: default
    name: "MetaBuilder Laptop Pro 16"
    description: "High-performance development laptop with 64GB RAM, M4 Max chip, and 1TB SSD. Ideal for running Docker containers, compiling C++ projects, and Next.js development."
    price: 3499.99
    salePrice: 2999.99
    imageUrl: "/images/products/laptop-pro.webp"
    category: Electronics
    sku: "MB-LP16-001"
    stock: 42
    featured: true
    isActive: true
    createdAt: 0
    updatedAt: 0

  - id: prod_mech_keyboard
    tenantId: default
    name: "TypeForge Mechanical Keyboard"
    description: "Cherry MX Brown switches, RGB backlit, USB-C, hot-swappable. Designed for long coding sessions with ergonomic wrist rest."
    price: 189.99
    imageUrl: "/images/products/keyboard.webp"
    category: Peripherals
    sku: "MB-KB-001"
    stock: 156
    featured: true
    isActive: true
    createdAt: 0
    updatedAt: 0

  - id: prod_4k_monitor
    tenantId: default
    name: "CodeView 32\" 4K Monitor"
    description: "32-inch 4K IPS display with USB-C PD 96W, HDR600, 99% sRGB. Multiple code windows side by side."
    price: 799.99
    salePrice: 699.99
    imageUrl: "/images/products/monitor.webp"
    category: Electronics
    sku: "MB-MON32-001"
    stock: 73
    featured: false
    isActive: true
    createdAt: 0
    updatedAt: 0

  - id: prod_standing_desk
    tenantId: default
    name: "DevDesk Pro Standing Desk"
    description: "Electric sit-stand desk, 60x30 inches, programmable height presets, cable management tray. Bamboo top."
    price: 649.99
    imageUrl: "/images/products/desk.webp"
    category: Furniture
    sku: "MB-DSK-001"
    stock: 28
    featured: false
    isActive: true
    createdAt: 0
    updatedAt: 0

  - id: prod_webcam_hd
    tenantId: default
    name: "StreamPro 4K Webcam"
    description: "4K 60fps webcam with auto-focus, AI background blur, low-light correction. USB-C plug and play."
    price: 149.99
    imageUrl: "/images/products/webcam.webp"
    category: Peripherals
    sku: "MB-WC4K-001"
    stock: 89
    featured: false
    isActive: true
    createdAt: 0
    updatedAt: 0

  - id: prod_headphones
    tenantId: default
    name: "FocusZone ANC Headphones"
    description: "Active noise cancelling, 40-hour battery, Bluetooth 5.3, multipoint connection. Foldable design."
    price: 279.99
    salePrice: 229.99
    imageUrl: "/images/products/headphones.webp"
    category: Audio
    sku: "MB-HP-001"
    stock: 204
    featured: true
    isActive: true
    createdAt: 0
    updatedAt: 0

  - id: prod_usbc_hub
    tenantId: default
    name: "DevHub 12-in-1 USB-C Hub"
    description: "12 ports including dual HDMI 4K60, Ethernet, SD/microSD, 3x USB-A, 2x USB-C PD 100W."
    price: 89.99
    imageUrl: "/images/products/usbhub.webp"
    category: Peripherals
    sku: "MB-HUB12-001"
    stock: 312
    featured: false
    isActive: true
    createdAt: 0
    updatedAt: 0

  - id: prod_ergo_mouse
    tenantId: default
    name: "ErgoTrack Vertical Mouse"
    description: "Ergonomic vertical design, 4000 DPI optical sensor, Bluetooth + 2.4GHz dual mode, silent clicks."
    price: 59.99
    imageUrl: "/images/products/mouse.webp"
    category: Peripherals
    sku: "MB-MSE-001"
    stock: 445
    featured: false
    isActive: true
    createdAt: 0
    updatedAt: 0

metadata:
  bootstrap: false
  skipIfExists: true
  timestampField: createdAt
  useCurrentTimestamp: true
