LAYER_SERVICE_RULES = {
    "2 Layer": {
        "Minimum Clearance": "6mil (0.1524mm)",
        "Minimum track Width": "6mil (0.1524mm)",
        "Minimum Connection Width": "6mil (0.1524mm)",
        "Minimum Annular Ring": "5mil (0.127mm)",
        "Minimum Via Diameter": "20mil (0.508mm)",
        "Copper to hole clearance": "5mil (0.127mm)",
        "Minimum Through Hole": "10mil (0.254mm)",
        "Hole to hole clearance": "5mil (0.127mm)",
        "Minimum uVia diameter": "20mil (0.508mm)",
        "minimum uVia Hole": "10mil (0.254mm)",
        "Silkscreen Min Item Clearance": "user preference",
        "Silkscreen Min Text Height": "user preference",
        "Silkscreen Min Text Thickness": "5mil (0.127mm)",
    },
    "4 Layer": {
        "Minimum Clearance": "5mil (0.127mm)",
        "Minimum track Width": "5mil (0.127mm)",
        "Minimum Connection Width": "5mil (0.127mm)",
        "Minimum Annular Ring": "4mil (0.1016mm)",
        "Minimum Via Diameter": "18mil (0.4572mm)",
        "Copper to hole clearance": "5mil (0.127mm)",
        "Minimum Through Hole": "10mil (0.254mm)",
        "Hole to hole clearance": "5mil (0.127mm)",
        "Minimum uVia diameter": "18mil (0.4572mm)",
        "minimum uVia Hole": "10mil (0.254mm)",
        "Silkscreen Min Item Clearance": "any",
        "Silkscreen Min Text Height": "any",
        "Silkscreen Min Text Thickness": "5mil (0.127mm)",
    },
    "6 Layer": {
        "Minimum Clearance": "5mil (0.127mm)",
        "Minimum track Width": "5mil (0.127mm)",
        "Minimum Connection Width": "5mil (0.127mm)",
        "Minimum Annular Ring": "4mil (0.1016mm)",
        "Minimum Via Diameter": "16mil (0.4064mm)",
        "Copper to hole clearance": "5mil (0.127mm)",
        "Minimum Through Hole": "8mil (0.2032mm)",
        "Hole to hole clearance": "5mil (0.127mm)",
        "Minimum uVia diameter": "16mil (0.4064mm)",
        "minimum uVia Hole": "8mil (0.2032mm)",
        "Silkscreen Min Item Clearance": "any",
        "Silkscreen Min Text Height": "any",
        "Silkscreen Min Text Thickness": "5mil (0.127mm)",
    },
}
